### ISSUE TITLE
How can I extend the packagist CSV schema?

### ISSUE THREAD

**Issue by richhall** [frictionlessdata/datapackage-ui#168]
Hi,

If I want to extend the CSV resource fields beyond 
- name
- type
- format

shown here:

![image](https://cloud.githubusercontent.com/assets/1749835/10416430/220292e2-700f-11e5-8907-14d9ee0f8600.png)

to include other fields from the http://dataprotocols.org/json-table-schema/ schema is this possible through the configuration of the packagist or do I need to make source code changes?

**Comment by pwalsh** [comment]
Hi @richhall it is not configurable, no, as the object here is the result of a guess (inference), and the other fields can't be guessed. Which other fields would you like to be able to add?

**Comment by richhall** [comment]
@pwalsh Thanks for answering this.  In the case of the example dataset I have been testing a column description would be nice (appreciating fully that the tool can't be expected to infer this).  What I was thinking was that portal owners could specify a template schema containing the CSV fields that they want to support within the tool.  Those extra fields would then appear for filling in.  Also, if the the package_show API shows an existing resource called datapackage.json then if possible that should be used as a default (as it may contain pre-filled descriptions etc which nobody would want to re-author).  This would allow a portal user to update and revalidate a datapackage.  

This needs a bit more thought as clearly adding fields lengthens the form and we need to get the UX right on that.  Let's park this for now as we get the fundamentals working.  We can arrange a catch up call to pick up.

**Comment by pwalsh** [comment]
@richhall ok great. Apart from the various stub issues I have on the tracker now, if you have other UX issues, please note them. Even if it possible duplicates another issue. Thanks.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
