### ISSUE TITLE
Support for Field Constraints?

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/datapackage-ui#199]
Are there any plans to support [field constraints](http://dataprotocols.org/json-table-schema/#field-constraints)?

It would be really cool if the field constraint could be defined by referencing a code library of common patterns (e.g. Australian Post Codes [as discussed in the Data Packages forum](https://discuss.okfn.org/t/w3c-csv-for-the-web-how-does-it-relate-to-data-packages/1715/4?u=stephen)).

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
