### ISSUE TITLE
Make Item names more meaningful

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/datapackage-ui#211]
Change the labels to reflect what the actually are...

![item name](https://cloud.githubusercontent.com/assets/9379524/12413338/eaf476d4-bed9-11e5-9395-5471806f08e3.PNG)

**Comment by pwalsh** [comment]
@Stephen-Gates I *love* the font in your screenshot :)

**Comment by Stephen-Gates** [comment]
@pwalsh I'm practising my calligraphy. I'll keep practising ;-)

**Comment by pwalsh** [comment]
We'll do this for sure.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
