### ISSUE TITLE
Validate Resources Header error

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/datapackage-ui#212]
Uploaded data file to generate datapackage.
Downloaded OK. Validated OK. 
Validate Resource throws an error.

![validation](https://cloud.githubusercontent.com/assets/9379524/12413507/157b698e-bedb-11e5-8b0f-ab2ada5da46f.PNG)

I don't think I changed any of the Field names but did edit some Field Titles.

I noticed a strange behaviour. When I CTRL+C in the Field name, it copies the name to the Title with some minor changes (drops brackets and changes capitalisation). Sometimes when I edit the Title, the same edits reflect in the Name field (using Chrome).  So editing Title may have changed name but I can't see any difference when I look at the csv file headers.

I would be good if the error message said what column the error is in.

**Comment by pwalsh** [comment]
Will check. Can you please add here the file, or a link to the file.

**Comment by Stephen-Gates** [comment]
@pwalsh Will do but will be tomorrow. File at work.

**Comment by Stephen-Gates** [comment]
@pwalsh recreated with https://github.com/Stephen-Gates/Stephen-Gates.github.io/blob/master/data/TidalStations.csv resulting in similar error.

In this case I did not edit any Field Titles

<img width="1264" alt="screenshot 2016-01-19 21 26 10" src="https://cloud.githubusercontent.com/assets/9379524/12417362/4fecd964-bef3-11e5-869b-5f3a4e3f1b74.png">

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
