### ISSUE TITLE
Loading resource from URL sometimes doesn't complete

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/datapackage-ui#213]
In Chrome and Safari I provided: 
-  a dataset name and title 
- then uploaded a resource using a URL.  

I get a Loading... screen and the task does not complete.

I tried:
- http://australia.census.okfn.org/api/entries.cascade.csv - fail
- http://www.tmr.qld.gov.au/~/media/aboutus/corpinfo/Open%20data/flashingschoolzonesigns via [this CKAN resource](https://data.qld.gov.au/dataset/installed-flashing-school-zone-signs/resource/ae1a7ded-e60f-49ad-b464-a8e8b5042a2e) on data.qld.gov.au - success.

I downloaded the census dataset and tried uploading the .CSV from my computer - fail

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
