### ISSUE TITLE
No use of datapackage-init-js

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/datapackage-ui#216]
Noticed that this app has no deps at all on datapackage-init-js

I would imagine that one would as datapackage-init is the underlying library. Worth detailing reasons why we are not and if there any plans to connects the two (e.g. to backport from here to the underlying lib).

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
