### ISSUE TITLE
"Read how it works" contains lorem ipsum

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/datapackage-ui#217]
Suggest we delete "Read how it works" and add "Documentation" link to top navbar that links to README here.

**Comment by roll** [comment]
True story but friend of mine found this "lorem ipsum" when was exploring frictonlessdata.io. So he's failed to create his first data package.

**Comment by rgrp** [comment]
@roll ++1 - i tried to fix this back in April and struggled to understand datapackagist code.

One option btw is to take down datapackagist whilst we refactor and put back up https://github.com/frictionlessdata/datapackage-init-js/tree/master/demo

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
