### ISSUE TITLE
1-2-3 logic could be confusing

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-ui#220]
Based on small user testing with my friend aside #217 we've found that 1-2-3 scenario with first step is OPTIONAL could be confusing:
1. Select an existing datapackage.json (it's really optional, the most users don't need it)
2. Choose a Data Package Profile
3. Edit the Data Package

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
