### ISSUE TITLE
Flag validation errors on uploaded datapackage.json descriptors

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-ui#221]
The following `datapackage.json` file has, for example, an invalid type "int" set on a resource.  This is silently dropped from the Data Package on upload.  If datapackagist is meant to be a Data Package validation tool as well a Data Package creation tool, it should at least show the users what is wrong with their existing Data Package descriptor.

https://github.com/datasets/world-cities/blob/3c89b6196cd00356e1cb3e40bc3b1d2aeb550198/datapackage.json

~~An aside: if invalid an Data Package can't be generated or edited using the tool, is there a point to an explicit "Validate" button?~~

**Comment by pwalsh** [comment]
put your aside in a distinct issue :)

thanks @danfowler

**Comment by danfowler** [comment]
I realize that the "Validate" button does, in fact, work for when some fields are incorrectly filled out.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
