### ISSUE TITLE
Support for custom DataPackage schemas

### ISSUE THREAD

**Issue by cyberbikepunk** [frictionlessdata/datapackage-ui#222]
The web app currently supports `base`, `tabular` and `fiscal` schemas by default. It would be great of we could support any schema. So long as the user has the JSON ready: we could offer to upload it.

**Comment by danfowler** [comment]
Hi @cyberbikepunk the schemas are sourced from this CSV file: https://github.com/frictionlessdata/schemas#the-registry

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
