### ISSUE TITLE
Support for Foreign Keys

### ISSUE THREAD

**Issue by sirex** [frictionlessdata/datapackage-ui#223]
Add support for [foreign keys](http://specs.frictionlessdata.io/json-table-schema/#foreign-keys).

**Comment by Stephen-Gates** [comment]
So this would this ensure the foreign key:

- is correctly specified
- exists as a field in another table within the datapackage?

We're hand-crafting foreign keys at present. We'd love to be able to use Good Tables to validate [referential integrity](https://en.wikipedia.org/wiki/Referential_integrity) across the two CSV files but understand this is a [rabbithole](https://github.com/frictionlessdata/goodtables/issues/8).

**Comment by pwalsh** [comment]
@sirex @Stephen-Gates 

This is really a [goodtables](https://github.com/frictionlessdata/goodtables) issue, as DataPackagist uses GodTables over an API for the work it does on data in resources.

@roll is currently refactoring GoodTables which brings lots of goodies including complete coverage of the JSON Table Schema spec.

**Comment by Stephen-Gates** [comment]
@pwalsh I was assuming that @sirex was looking for a feature in the UI to add a foreign key. 
I may have confused things by referencing Good Tables.

You don't seem to be able to add keys through the UI but if you upload a datapackage.json, they are displayed. 

![image](https://cloud.githubusercontent.com/assets/9379524/18660250/c569053a-7f52-11e6-8609-ca4da83173c3.png)

**Comment by pwalsh** [comment]
@Stephen-Gates ok I see, right. We'll look at it soon.

**Comment by sirex** [comment]
Yes, I could not find a field, where I can specify a foreign key. Thanks @Stephen-Gates for pointing this out.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
