### ISSUE TITLE
"schema": "http://example.com/schema.json" is not correct?

### ISSUE THREAD

**Issue by CharlesNepote** [frictionlessdata/datapackage-ui#224]
Maybe I didn't understand [this part of the spec](http://specs.frictionlessdata.io/data-packages/#schema-references) but I thought it would be possible to provide a URL for the schema (instead of describing the schema).

See the [following example in real](https://gist.githubusercontent.com/CharlesNepote/dcc9549a3c1c71a4d155a6df02fc7f3c/raw/c6a50986201513c852021277fa608a551993c527/datapackage.json).

1. Datapackagist app at http://datapackagist.okfnlabs.org/ doesn't take my "schema" in account when I "Select an existing datapackage.json".
2. Datapackage Validator is [showing an error I don't understand](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgist.github.com%2FCharlesNepote%2Fdcc9549a3c1c71a4d155a6df02fc7f3c%2Fraw%2Fc6a50986201513c852021277fa608a551993c527%2Fdatapackage.json).

Is it a bug or I've done something wrong?

**Comment by pwalsh** [comment]
Hi @CharlesNepote while the spec does support a URL, the implementation behind http://datapackagist.okfnlabs.org/ still only supports an inlined schema. This will be updated when the specs hit v1 in January

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
