### ISSUE TITLE
Read How it Works - pops up lorem ipsum

### ISSUE THREAD

**Issue by jeremydouglass** [frictionlessdata/datapackage-ui#229]
The homepage on http://datapackagist.openknowledge.io reads:

> Read **how it works**, or jump straight in.

Clicking the link produces a pop-up full of lorem ipsum.

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec lectus consequat, blandit ipsum vitae, efficitur lectus. Nam ut interdum lorem, quis porta orci. Phasellus varius sit amet metus vitae porta. Vestibulum a nunc quis magna aliquet sagittis sagittis ac sapien. Nullam convallis, mauris ut tempor fringilla, risus est dignissim lacus, in aliquet orci nulla ac nisi. Ut tincidunt sagittis finibus. In pharetra, lorem vitae aliquam dictum, elit ipsum efficitur ante, in finibus felis diam quis justo. Pellentesque tellus nisi, placerat vel nisl nec, porta posuere lectus. Aenean faucibus varius mauris in varius. Pellentesque vitae quam et nisi accumsan viverra in id ante. Ut non massa sem.
> 
> Curabitur pretium nisl in urna consectetur placerat. Quisque vel est nibh. Sed molestie ultricies ante a imperdiet. Vivamus condimentum dui a commodo congue. Quisque vehicula orci quis velit aliquet scelerisque. Fusce luctus pellentesque ante, sed pharetra lorem gravida sed. Nulla elementum justo nec ligula efficitur dapibus. Phasellus vitae dolor in metus feugiat viverra vitae in nunc. Nullam congue ex tristique malesuada scelerisque. Nunc luctus mi in ipsum auctor iaculis. Quisque vitae vestibulum lacus, sit amet sollicitudin est.

The culprit is probably:

-  datapackagist/dist/how-it-works.md

**Comment by roll** [comment]
@jeremydouglass 
Thanks for reporting. We're starting a re-work for the whole application so it could be fixed soon here - https://github.com/frictionlessdata/datapackage-ui/issues/227

**Comment by roll** [comment]
I've added a check point for it to the main issue.
