### ISSUE TITLE
Rename Packagist -> Data Package Creator

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-ui#245]
@smth We moved this to https://create.frictionlessdata.io, so "Packagist.io" doesn't work anymore. I tried to change the SVG logo myself, but couldn't as the text is in paths. Could you do it?

The issues is that "Data Package Creator" is much bigger than "Packagist", so we'll need to be creative.

**Comment by smth** [comment]
Sounds like this is moving away from having it's own identity. In which case, it should probably identify as part of Frictionless Data. So maybe we do something like:

<img width="561" alt="datapackagist_02" src="https://user-images.githubusercontent.com/1375708/35481948-97f731ae-0425-11e8-991b-447443d82093.png">

**Comment by smth** [comment]
I've added a branch here https://github.com/frictionlessdata/datapackage-ui/compare/fd-identity which should contain all the necessary changes to implement the above (as well some CSS vendor prefix updates). I have **not tested** this in this codebase, so it needs checking.
