### ISSUE TITLE
Incorrect validation error on tabular data package

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-ui#248]
1. Go to https://create.frictionlessdata.io
1. Add the resource https://raw.githubusercontent.com/frictionlessdata/example-data-packages/master/gross-domestic-product-2014/data/gdp_2014.csv
1. Click on "Add all inferred fields"
1. Add a "name" as "gdp" and "title" as "Countries GDP"
1. Click on "Validate"

The following error is raised:

```
Data package is invalid!
* Descriptor validation error: Data does not match any schemas from "oneOf" at "/resources/0" in descriptor and at "/properties/resources/items/oneOf" in profile
```

Validating the same generated datapackage with `goodtables` is successful. This is the generated datapackage:

```json
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "name": "resource1",
      "path": "https://raw.githubusercontent.com/frictionlessdata/example-data-packages/master/gross-domestic-product-2014/data/gdp_2014.csv",
      "schema": {
        "fields": [
          {
            "name": "Country Name",
            "type": "string",
            "format": "default"
          },
          {
            "name": "Country Code",
            "type": "string",
            "format": "default"
          },
          {
            "name": "Year",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Value",
            "type": "integer",
            "format": "default"
          }
        ]
      }
    }
  ],
  "name": "gdp",
  "title": "gdp-data"
}
```

**Comment by serahrono** [comment]
@vitorbaptista 

I came across this same issue, and @roll pointed me in the right direction. At this time, one has to specify the profile of each data resource from the resource settings image, see image below. 

<img width="458" alt="data resource profile" src="https://user-images.githubusercontent.com/4550385/35925315-1658c430-0c2e-11e8-9c65-6c940a00e2f0.png">

**Comment by roll** [comment]
The profile is now inferred in underlying libs so the scenario in the first comment works
