### ISSUE TITLE
Data Package Creator misinterprets empty string as null value

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/datapackage-ui#260]
When using the [Data Package Creator web UI](https://create.frictionlessdata.io), if you load a package that contains a tabular data resource explicitly specifying `missingValues` that include the empty string `""`, this value is interpreted by the validator and for preview display in the right sidebar as a `null` rather than an empty string. In some cases this causes validation of the data package to fail, with an error declaring that the `null` value is invalid, because `missingValues` is supposed to be an array of strings. However, it only does this sometimes, and I haven't been able to figure out why.

**Comment by augusto-herrmann** [comment]
One way to reproduce this bug is:
```bash
$ mkdir issue-260
$ cd issue-260
$ python3 -m venv pyenv
$ source pyenv/bin/activate
$ pip3 install datapackage
$ echo -e "number,color\n1,black\n2,white\n" > test.csv
$ datapackage infer test.csv > datapackage.json
```

Then upload `datapackage.json` into the UI, and download it again. Try to validate the file and you get:

> Data package is invalid!
> * Descriptor validation error: Invalid type: undefined (expected string) at "/resources/0/schema/missingValues/0" in descriptor and at "/properties/resources/items/properties/schema/properties/missingValues/items/type" in profile
