### ISSUE TITLE
Add possibility to add buttons to datapackage-ui by an integrator

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/datapackage-ui#268]
As part of https://github.com/frictionlessdata/schema-collaboration I need to load datapackage-ui instance with some extra features:

The extra features are:
 * Add a button to "Save" the existing package using an API to a server
 * Add a button to "Load" a package from a server using an API
 * If a package identification is passed to datapackage-ui via a URL parameter: a Javascript function would need to be called (to Load it from the server)

In the future: the same with the example resource.

This was done in a hacky way for the schema-collaboration prototype:
https://github.com/frictionlessdata/datapackage-ui/compare/master...cpina:master

In order to this in a maintainable way I had thought that datapackage-ui could have a "plugin" or "extension" system: a documented way for an "integrator" to do:
 * add buttons on the left hand side panel that call Javascript written by the integrator of datapackage-ui
 * get the datapackage JSON from the running datapackage-ui
 * set the a datapackage into the running datapackage-ui
 * add a function that is called once datapackage-ui has been loaded: the integrator can read the query string, get the datapackage ID, get it from the API, set it into the datapackage-ui (alternatively the query string breaking up could be done by datapackage-ui and call a function with the ID)

And last thing (not in the example that I sent above):
 * set/get operations for the resource file (I haven't properly looked at this but it would be similar to loading/saving the datapackage)

I've broken down the operations as described so the integrators have full freedom on how to do the Load and Save regarding APIs, authentication flows, feedback to the user after the save is done or if there is an error, etc. Obviously an example with a hard coded JSON package doing a set and get would help integrators to know what to do.

Please ask me if anything is not clear.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @cpina, do I understand correctly that, for now, it's not blocking? 

I'll be off for a week and a half from next week and probably I will not enough time before to implement it. But I can start implementing the feature when I'm back

**Comment by cpina** [comment]
> Thanks @cpina, do I understand correctly that, for now, it's not blocking?

correct, this is not blocking for now (I'm using the "hacky" way for now in my repo and focusing on other parts of the application).

> I'll be off for a week and a half from next week and probably I will not enough time before to implement it. But I can start implementing the feature when I'm back

No problem at all! Actually I'm off for 2 weeks starting next week :-)

Thanks very much!

**Comment by cpina** [comment]
Besides the original bullet points:

It would be nice if users of datapackage-ui (like schema-collaboration) could add certain variables on left hand side panel. E.g. int he Swiss Polar Institute we are asking the "Quality Checking". My first idea would be something like:
```
{
    "field_name": 'x_spi_quality_checking",
    "label": "Quality checking",
    "help_text": "Please describe how the data was quality checked"
}
```

I've also thought of filling this extra-fields on the Django side using a form and on the "Download datapackage schema" these fields could be embedded. Obviously these fields would be configurable per installation.

I'm happy to open a new issue with this (as this is less needed than the original bullet points).
