### ISSUE TITLE
Display error if a datapackage cannot be loaded

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/datapackage-ui#274]
# Overview

Steps to reproduce:
 * Download https://raw.githubusercontent.com/Swiss-Polar-Institute/frictionless-data-packages/562802f045697ed14ac75d994a17f9a21ecbbbbe/10.5281_zenodo.2635685/datapackage.json
 * Open https://create.frictionlessdata.io/
 * Click on "Upload" and select the previous file

I expected:
 * It either works...
 * Or datapackage creator shows an error (JSON error? missing mandatory field? unsupported profile?)

What happened:
 * No feedback to the user
 * I see an exception in the Javascript console

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks. I'll fix it

**Comment by roll** [comment]
The problem was with the `resource[].schema` property which needs to be ignored if it's a string (we can't dereference it in the browser)
