### ISSUE TITLE
"Title" and "name" fields are not read from a datapackage description

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/datapackage-ui#278]
# Overview

 * Download https://raw.githubusercontent.com/Swiss-Polar-Institute/frictionless-data-packages/master/10.5281_zenodo.2635685/datapackage.json
 * Open https://create.frictionlessdata.io/
 * Click on "Upload" and upload the file downloaded previously

I expected "title" and "name" (left hand side panel) to be read from the package (Homepage, version, license is read)

"title" and "name" are not read.

I've tried earlier another datapackage where "name" was read but not "title".

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, I'll investigate

**Comment by roll** [comment]
![dp1](https://user-images.githubusercontent.com/557395/101326603-cacdae80-386d-11eb-9fca-019b6d5fff37.png)
![dp2](https://user-images.githubusercontent.com/557395/101326612-cdc89f00-386d-11eb-98b6-42297a955ded.png)

**Comment by roll** [comment]
Hi @cpina,

I can't reproduce it in both Chrome and Firefox. Can you please try removing cookies etc and uploading it again in your environment?

Please re-open if you still are getting the bug

**Comment by cpina** [comment]
I'll do this tomorrow, thanks roll
(@cpina)

**Comment by cpina** [comment]
Confirmed that I can't reproduce with any of my browsers (even with my default Firefox with last week's cookies). Thanks for checking.
