### ISSUE TITLE
Package's name and title visually marked as mandatory (they are not)

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/datapackage-ui#279]
# Overview

 * Open any datapackage
 * Delete the contents in "title" or "name"
 * Click on validate: it says "Data package is valid!"

"Title" and "name" are mandatory fields so I think that it should not be valid.

If I write, in "name", invalid text it says:
    "Descriptor validation error: String does not match pattern: ^([-a-z0-9._/])+$ at "/name" in descriptor and at "/properties/name/pattern" in profile"

I think that the same type of error would be fine (but I think that in longer term making the errors easier to understand for users not reading reg exp might be useful as well)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @cpina,

I think it's not mandatory:

> https://specs.frictionlessdata.io/data-package/#descriptor

```
A Data Package descriptor MUST be a valid JSON object. (JSON is defined in RFC 4627). When available as a file it MUST be named datapackage.json and it MUST be placed in the top-level directory (relative to any other resources provided as part of the data package).

The descriptor MUST contain a resources property describing the data resources.

All other properties are considered metadata properties. The descriptor MAY contain any number of other metadata properties. The following sections provides a description of required and optional metadata properties for a Data Package descriptor.
```

**Comment by roll** [comment]
For validation, we use an official JSON Schema from the specs site so it should be accurate

**Comment by cpina** [comment]
> Hi @cpina,
> 
> I think it's not mandatory:

Oh, you are right! (I've just checked that datapackage.Package.is_valid agrees)

In this case the star (*) next to "Name" and "Title" should probably not be there.

**Comment by roll** [comment]
Yea, thanks, I'll fix it
